services:
  profiledb:
      image: postgres:16
    
  profileserviceglobal:
    image: ${DOCKER_REGISTRY-}profileserviceglobal
    build:
      context: .
      dockerfile: ProfileServiceGlobal/Dockerfile
  profilegateway:
    image: ${DOCKER_REGISTRY-}profilegateway
    build:
      context: .
      dockerfile: ProfileGateway/Dockerfile

volumes:
    postgress_profile:
